### PR TITLE
Fix remaining Windows tests

### PR DESCRIPTION
**Pull request by kohenkatz**

### CODE REVIEW

**Comment by kohenkatz** [comment]
Weirdly, this fails in Node 6.x on Windows with a different hash for one of the files. Any thoughts?

**Comment by tpraxl** [comment]
Thanks for your contribution. I'll look into it as soon as I can. Might be not tonight though.

**Comment by tpraxl** [comment]
Well.. vendor.js is in this case the extracted vue library. I cannot see any way that there is something to be extracted. Also, I guess, there is no /js/vendor.js at all. And that may cause differences in the hash depending on the node version. But I need to check that. Why did you use `path.posix.join`? I'm not familiar with `path.posix`. Did you notice that you didn't use that in the `hash` function? (But I tested it, it wouldn't fix the failing test in node6).

**Comment by kohenkatz** [comment]
`path.posix` forces it to use `/` instead of `\\`. The reason I used it there is because that path is for the browser which always needs forward slashes. It's just an easy way of not needing to replace the slashes afterwards.

I am wondering if Node 6.x is doing something with the line endings of the file that is causing the hash to change, but I haven't had time to check yet.

**Comment by tpraxl** [comment]
Did a bit of research. The file actually contains quite a bit of extracted code. Seems to be webpack stuff. See attachment.

[content-of-vendor-js.txt](https://github.com/tpraxl/laravel-mix/files/1647337/content-of-vendor-js.txt)

**Comment by tpraxl** [comment]
Well at least *something* seems to have changed between node 6 and 7: https://github.com/nodejs/node/issues/9671 

This is a nasty problem. It could be solved by changing the tests to be less specific about the exact hashes.

**Comment by tpraxl** [comment]
I just verified the hashes for older builds: Your change didn't make things worse. The "wrong" hash has been in node 6 on windows before. So I'm gonna merge this. Thanks for your help. Further help is very welcome.

**Comment by tpraxl** [comment]
@kohenkatz FYI: See https://github.com/tpraxl/laravel-mix/issues/3

**Pull request merged**
